# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20170520_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrado',
            old_name='nombre',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='registrado',
            name='codigo_postal',
        ),
    ]
